Public Class TXTEMLA
    Shared Sub TXTEMLA(TXT)
        I = 1
        Dim r1 As String = Replace(TXT, "أ", "ا")
        Dim r2 As String = Replace(r1, "ى", "ي")
        Dim r3 As String = Replace(r2, "ة", "ه")
        Dim r4 As String = Replace(r3, "عبدا", "عبد ا")
        Dim r5 As String = Replace(r4, "ربالل", "ر بالل")
        Dim r6 As String = Replace(r5, "مبالل", "م بالل")
        Dim r7 As String = Replace(r6, "ءال", "ء ال")
        Dim r8 As String = Replace(r7, "عزالدين", "عز الدين")
        Dim r9 As String = Replace(r8, "نورالدين", "نور الدين")
        Dim r10 As String = Replace(r9, "زينالعابدين", "زين العابدين")
        Dim r11 As String = Replace(r10, "نورالهدي", "نور الهدى")
        Dim r12 As String = Replace(r11, "نور الهدي", "نور الهدى")
        Dim r13 As String = Replace(r12, "هبةالله", "هبة الله")
        Dim r14 As String = Replace(r13, "هبهالله", "هبة الله")
        Dim r15 As String = Replace(r14, "هبه الله", "هبة الله")
        Dim r16 As String = Replace(r15, "خيرالله", "خير الله")
        Dim r17 As String = Replace(r16, "فتحالله", "فتح الله")
        Dim r18 As String = Replace(r17, "رؤي", "رؤى")
        Dim r19 As String = Replace(r18, "نهي", "نهى")
        Dim r20 As String = Replace(r19, "ندي", "ندى")
        Dim r21 As String = Replace(r20, "ضحي", "ضحى")
        Dim r22 As String = Replace(r21, "مني ", "منى ")
        Dim r23 As String = Replace(r22, "منىه", "منيه")
        Dim r24 As String = Replace(r23, "منىر", "منير")
        Dim r25 As String = Replace(r24, "منىب", "منيب")
        Dim r26 As String = Replace(r25, "سجي", "سجى")
        Dim r27 As String = Replace(r26, "سهي", "سهى")
        Dim r28 As String = Replace(r27, "رؤىه", "رؤيه")
        Dim r29 As String = Replace(r28, "سندىانه", "سنديانه")
        Dim r30 As String = Replace(r29, "سندىان", "سنديان")
        Dim r31 As String = Replace(r30, "سهىل", "سهيل")
        Dim r32 As String = Replace(r31, "جني", "جنى")
        Dim r33 As String = Replace(r32, "منىه", "منيه")
        Dim r34 As String = Replace(r33, "بشري", "بشرى")
        Dim r35 As String = Replace(r34, "المثني", "المثنى")
        Dim r36 As String = Replace(r35, "اروي", "اروى")
        RTXT = Trim(r36)
    End Sub
End Class
